### PR TITLE
Bunch of minor usability improvements here and there

### PR DESCRIPTION
**Pull request by piotrrak**

### CODE REVIEW

**Comment by piotrrak** [comment]
Please let me know if you want any of those.

**Comment by qookei** [comment]
These all seem good to me. Does managarm compile with these changes applied?

**Comment by piotrrak** [comment]
Yea, 0001 branches have no dependencies.

**Comment by ArsenArsen** [comment]
does this align with previous commit message discipline?

**Comment by Geertiebear** [comment]
Also make sure mlibc compiles with these changes.

**Comment by avdgrinten** [comment]
@ArsenArsen Do you mean the branch name? That is fine IMHO.

Regarding the changes: they all look fine to me. For quantifying the `optional::value()` function: when does this make a difference? This only really affects code that directly passes .value() into a function taking a rvalue reference, right? (Since `std::move(foo.value())` already gave a rvalue reference before.)

**Comment by piotrrak** [comment]
> Regarding the changes: they all look fine to me. For quantifying the `optional::value()` function: when does this make a difference? This only really affects code that directly passes .value() into a function taking a rvalue reference, right? (Since `std::move(foo.value())` already gave a rvalue reference before.)

One common case would be:
```
optional<T> foo();

T t1 = foo().value();
// You sure could without it:
T t2 = std::move(foo().value()); 
```

**Comment by avdgrinten** [comment]
Makes sense. LGTM.

**Comment by piotrrak** [comment]
Will resubmit split per modules with more explanatory and consistent commit messages tonight/tomorrow.

**Comment by piotrrak** [comment]
> Also make sure mlibc compiles with these changes.

mlibc also builds with those changes

**Review by Geertiebear — APPROVED** [review]
Okay then LGTM.

**Pull request merged**
