### PR TITLE
add lvalue ref support to tuples

### PR DESCRIPTION
**Pull request by ArsenArsen**

### CODE REVIEW

**Comment by ArsenArsen** [comment]
wait, this is nonsense

**Review by avdgrinten — COMMENTED** [review]
Is this implementation *correct*? You pass `T` to `std::forward` but `T` is a template parameter of the class, not of the function. Doesn't this implementation always cast to a rvalue reference?

**Comment by ArsenArsen** [comment]
In the case of T being an lvalue reference, collapsing rules result in a cast to std::remove_reference_t<T>&, causing the reference to be copied. In all other cases, the resulting cast is to an rvalue reference.

I am not aware of any regressions, though my test cases were admittedly limited. I'm looking at expanding on a test suite to make it easier to know what's valid in the future.

**Review by qookei — APPROVED** [review]
LGTM

**Pull request merged**
