### PR TITLE
string: minor improvements and fixing operator== issues

### PR DESCRIPTION
**Pull request by no92**

### CODE REVIEW

**Comment by no92** [comment]
Reworked `operator==` due to a single instance of a line like `if(ret.name == "")` with ret.name being of type `frg::string<something>` in mlibc complaining. This solution is in line with what the C++ spec says (N4835 21.3.3.2 [string.cmp]).

**Comment by Geertiebear** [comment]
Does this change not cause the exact same warning that #18 fixed?

**Comment by no92** [comment]
To my own surprise, no. Both `managarm-kernel` and `mlibc` compile, the former (where the warning originally appeared) even with `-Wimplicit-fallthrough -Werror`.

**Review by Geertiebear — APPROVED** [review]
Alright, if both mlibc and managarm are verified to compile with this, then LGTM.

**Review by avdgrinten — APPROVED** [review]
LGTM.

**Pull request merged**
